export const BOARD_SELECTION_CLEAR = "BOARD_SELECTION_CLEAR";
export const BOARD_SELECT_DRAW = "BOARD_SELECT_DRAW";

export const BOARD_DRAGGING_ELEMENTS = "BOARD_DRAGGING_ELEMENTS";
export const BOARD_DROP_ELEMENTS = "BOARD_DROP_ELEMENTS";

export const BOARD_DRAW_ADD = "BOARD_DRAW_ADD";

export const BOARD_DRAW_START_RESIZE = "BOARD_DRAW_START_RESIZE";
export const BOARD_DRAW_RESIZE = "BOARD_DRAW_RESIZE";
export const BOARD_DRAW_STOP_RESIZE = "BOARD_DRAW_STOP_RESIZE";

export const BOARD_CONNECTOR_DRAWING_START = "BOARD_CONNECTOR_DRAWING_START";
export const BOARD_CONNECTOR_DRAWING = "BOARD_CONNECTOR_DRAWING";
export const BOARD_CONNECTOR_DRAWING_END = "BOARD_CONNECTOR_DRAWING_END";

//ConnectorActions
export const BOARD_SELECT_CONNECTOR = "BOARD_SELECT_CONNECTOR";

//KeyboardActions
export const BOARD_DELETE_PRESSED = "BOARD_DELETE_PRESSED";

//tabDrawList
export const DRAWLIST_CHANGE_SELECTED = "DRAWLIST_CHANGE_SELECTED";
export const DRAWLIST_DRAG_BLOCK = "DRAWLIST_DRAG_BLOCK";
export const DRAWLIST_DROP_BLOCK_OUT_OF_BOARD =
  "DRAWLIST_DROP_BLOCK_OUT_OF_BOARD";

//serverConnectionActions
export const SERVER_CONNECTION_READY = "SERVER_CONNECTION_READY";
export const SERVER_CONNECTION_BUSY = "SERVER_CONNECTION_BUSY";
export const SERVER_CONNECTION_DISCONNECTED = "SERVER_CONNECTION_DISCONNECTED";
