export const BOARD_ELEMENT_DRAGGING = "BOARD_ELEMENT_DRAGGING";
export const BOARD_ELEMENT_ADD = "BOARD_ELEMENT_ADD";

export const BOARD_CONNECTOR_DRAWING_START = "BOARD_CONNECTOR_DRAWING_START";
export const BOARD_CONNECTOR_DRAWING = "BOARD_CONNECTOR_DRAWING";
export const BOARD_CONNECTOR_DRAWING_END = "BOARD_CONNECTOR_DRAWING_END";
