export const BOARD_SELECTION_CLEAR = "BOARD_SELECTION_CLEAR";
export const BOARD_SELECT_DRAW = "BOARD_SELECT_DRAW";
export const BOARD_SELECT_ADD_DRAW = "BOARD_SELECT_ADD_DRAW";

export const BOARD_MOUSEDOWN_DRAW = "BOARD_MOUSEDOWN_DRAW";

export const BOARD_CLEAR_HIGHLIGHT_DRAW_DRAGGING =
  "BOARD_CLEAR_HIGHLIGHT_DRAW_DRAGGING";
export const BOARD_DRAGGING_ELEMENTS = "BOARD_DRAGGING_ELEMENTS";
export const BOARD_DROP_ELEMENTS = "BOARD_DROP_ELEMENTS";

export const BOARD_DRAW_ADD = "BOARD_DRAW_ADD";

export const BOARD_CONNECTOR_DRAWING_START = "BOARD_CONNECTOR_DRAWING_START";
export const BOARD_CONNECTOR_DRAWING = "BOARD_CONNECTOR_DRAWING";
export const BOARD_CONNECTOR_DRAWING_END = "BOARD_CONNECTOR_DRAWING_END";
